# Generated by Django 5.2.4 on 2025-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passengerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_column='Source', max_length=100)),
                ('destination', models.CharField(db_column='Destination', max_length=100)),
                ('train_name', models.CharField(db_column='Train_Name', max_length=150)),
                ('train_number', models.CharField(db_column='Train_Number', max_length=20)),
                ('departure_time', models.CharField(db_column='Departure_Time', max_length=20)),
                ('arrival_time', models.CharField(blank=True, db_column='Arrival_Time', max_length=20, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=50, null=True)),
                ('distance', models.CharField(blank=True, db_column='Distance', max_length=50, null=True)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('mobile_no', models.CharField(db_column='Mobile_No', max_length=20)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('berth_selected', models.CharField(db_column='Berth_Selected', default='Not Selected', max_length=30)),
                ('name', models.CharField(db_column='Name', max_length=120)),
                ('age', models.PositiveIntegerField(db_column='Age')),
                ('gender', models.CharField(db_column='Gender', max_length=20)),
                ('date_of_departure', models.DateField(db_column='Date_of_Departure')),
                ('date_of_arrival', models.DateField(blank=True, db_column='Date_of_Arrival', null=True)),
                ('booked_seat_number', models.CharField(db_column='Booked_Seat_Number', max_length=20)),
                ('train_class', models.CharField(db_column='Class', max_length=10)),
                ('quota', models.CharField(db_column='Quota', max_length=50)),
                ('fare', models.DecimalField(db_column='Fare', decimal_places=2, max_digits=10)),
                ('pnr_number', models.CharField(db_column='PNR_Number', max_length=10)),
                ('free_cancellation', models.BooleanField(db_column='Free_Cancellation', default=False)),
                ('refund_amount', models.DecimalField(db_column='Refund_Amount', decimal_places=2, max_digits=10)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, db_column='Cancelled_At')),
            ],
            options={
                'db_table': 'CancelledBooking',
                'indexes': [models.Index(fields=['pnr_number'], name='idx_cancel_pnr')],
            },
        ),
    ]
