# Generated by Django 5.2.4 on 2025-08-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cancelledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetails',
            name='gst_incl',
            field=models.DecimalField(db_column='GST_Incl', decimal_places=2, default=0, max_digits=10),
        ),
    ]
