# Generated by Django 5.2.4 on 2025-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('Train_id', models.AutoField(primary_key=True, serialize=False)),
                ('TrainNo', models.CharField(max_length=20, unique=True)),
                ('TrainName', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('TicketPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepartureTime', models.TimeField()),
                ('ArrivalTime', models.TimeField()),
            ],
        ),
    ]
