# Generated by Django 5.2.4 on 2025-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstatus',
            name='Classes',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainstatus',
            name='TicketPrice',
            field=models.CharField(max_length=300),
        ),
    ]
