# Generated by Django 5.2.4 on 2025-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainstatus', '0002_trainstatus_classes_alter_trainstatus_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstatus',
            name='Availability',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='DestinationCode',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='DistanceKM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='DurationDays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='DurationTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='RunningStatus',
            field=models.CharField(default='On Time', max_length=50),
        ),
        migrations.AddField(
            model_name='trainstatus',
            name='SourceCode',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
